development:
  adapter: postgresql
  encoding: utf8
  database: ibdb_dev
  pool: 5
  username: abraheem
  password: password

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: ibdb_test
  pool: 5
  username: abraheem
  password: password
